### ISSUE TITLE
graphql rename causes problems for webpack parser (Error: Cannot find module 'graphql/validation/rules/ExecutableDefinitions')

### ISSUE THREAD

**Issue by devkral** [Quramy/ts-graphql-plugin#634] opened 2021-11-01 23:55 UTC
---

name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
---**Describe the bug**
The graphql package renamed its validation rule(s).  This causes errors with this project, as e.g. 'graphql/validation/rules/ExecutableDefinitions' is linked.
This is the case with the webpack plugin

**Expected behavior**
use webpack plugin with newest graphql

'''Solution**
Update imports

**Comment by mizdra** [comment] 2021-11-09 04:03
I found out that the error was caused by the ts-graphql-plugin being incompatible with graphql v16. In my project, I lowered the version to graphql v15 and the problem went away.

**Comment by proteriax** [comment] 2022-02-05 20:47
I fixed the problem by appending`"graphql-language-service-interface": "2.10.2"` to the `resolutions` field of my `package.json` without downgrading to v15.

**Comment by Quramy** [comment] 2024-03-15 14:57
Close this because `graphql-language-service-interface` is no longer depended via https://github.com/Quramy/ts-graphql-plugin/pull/1202

**Closed by Quramy** 2024-03-15 14:57 UTC
